const defaultConfig = {
    //ordered like options.md
    'debug': {
        'atoms': true, 'showAtoms': false, 'edges': true, 'showEdges': false, 'textSize': 6.5
    },
    'geomineMode': false,
    'geomine': {
        'RingCenterColor': '#33cccc',
        'SecondaryStructureColor': '#ffd700',
        'interactionQueryDashDrawn': 1.5,
        'interactionQueryDashGap': 1.5
    },
    'allowInteraction': true,
    'allowedInteraction': [
        '',
        'movement',
        'rotation',
        'scaledRotation',
        'rectSelect',
        'freeSelect',
        'lineMirror',
        'bondMirror',
        'zoomIn',
        'zoomOut',
        'advanceHistory',
        'revertHistory',
        'center',
        'structureReset',
        'remove',
        'addIntermolecular',
        'addAnnotation',
        'globalMovement',
        'doNothing',
        'addStructure',
        'clickSelect',
        'addAtom',
        'edit'
    ],
    'excludedInteraction': [],
    'defaultInteraction': 'movement',
    'buttons': {
        'mouse': {
            'clickSelect': [{'key': 0, 'modifiers': []}],
            'rectSelect': [{'key': 0, 'modifiers': ['shift']}],
            'freeSelect': [{'key': 0, 'modifiers': ['ctrl']}],
            'remove': [{'key': 0, 'modifiers': ['alt']}],
            'rotation': [{'key': 1, 'modifiers': []}],
            'addAnnotation': [{'key': 1, 'modifiers': ['shift']}],
            'addIntermolecular': [{'key': 1, 'modifiers': ['ctrl']}],
            'addStructure': [{'key': 1, 'modifiers': ['alt']}],
            'movement': [{'key': 2, 'modifiers': []}],
            'bondMirror': [{'key': 2, 'modifiers': ['alt']}],
            'lineMirror': [{'key': 2, 'modifiers': ['ctrl']}],
        },
        'zoomIn': [{'type': 'wheel', 'button': 'up'}, {'type': 'key', 'button': '+'}],
        'zoomOut': [{'type': 'wheel', 'button': 'down'}, {'type': 'key', 'button': '-'}],
        'advanceHistory': [{'type': 'key', 'button': 'ArrowRight'}],
        'revertHistory': [{'type': 'key', 'button': 'ArrowLeft'}],
        'center': [{'type': 'key', 'button': 'c'}],
        'structureReset': [{'type': 'key', 'button': 'r'}],
        'remove': [{'type': 'key', 'button': 'Delete'}]
    },
    'moveFreedomLevel': 'structures',
    'moveAllSelection': true,
    'hoverAfterDeselection': true,
    'selectionGrace': 0.4,
    'scaledRotationThreshold': 5,
    'zoomStrength': 7,
    'sceneMaxScale': 3,
    'sceneMinScale': 0.5,
    'handleCollisionWith': 'selector',
    'historyCanClearScene': true,
    'addIntermolecularSnapDist': 15,
    'resetMode': 0,
    'allowedStructureRepresentations': {
        //also defines the order. first one gets set as initial
        'default': ['default', 'circle']
    },
    'structureCircleOpts': {
        'default': {
            'circleCss': {
                'stroke': '#000000', 'fill': '#808080', 'opacity': '0.4'
            },
            'rad': 20,
            'textColor': '#000000',
            'labelMaxLines': 3, //max 3 lines are implemented!
            'labelSameFontSize': true,
            'labelAutoSplit': true,
            'labelAutoSplitMinCharsPerLine': 3,
            'labelManualLineBreakChars': [" ", "-", "_"],
            'labelManualIncludeSplitChar': [false, false]
        }
    },
    'atomMode': 'name',
    'textSelector': 'full',
    'fontFamily': 'arial',
    'textSize': 6.5,
    'textCrop': '0.285em',
    'textBorderCorrection': 1,
    'labelSideCorrection': 1,
    'hOffset': '0.2em',
    'chargeFontSize': 0.775,
    'chargeOffset': 0.3,
    'hNumberFontSize': 0.6,
    'hNumberOffset': 0.235,
    'atomRadius': 3.75,
    'atomSelectorRadius': 5,
    'smallestBboxWidth': 20,
    'lineWidth': 0.65,
    'wedgeBaseWidth': 0.3,
    'wedgeFullWidth': 2.5,
    'wedgeSpacing': 1,
    'spaceBetweenDouble': 1.3,
    'spaceBetweenTriple': 0.75,
    'spaceToRing': 1.3,
    'cutoffAngleDouble': 60,
    'edgeSelectorOffset': 2.25,
    'lineDashDrawn': 2,
    'lineDashGap': 2,
    'colors': {
        'DEFAULT': '#222',
        'BACKGROUND': '#fff',
        'HOVER': '#8eff7d',
        'SELECTION': '#10ff00',
        'MIRROR': '#ff6600',
        'multiSelectionToolBorder': '#ff33ff',
        'multiSelectionToolFill': '#ffe6ff',
        'cationPiStackings': '#99cc33',
        'piStackings': '#33cccc',
        'atomPairInteractions': '#6699ff',
        'ionicInteractions': '#ff00ff',
        'metalInteractions': '#f7de3a',
        'hydrophobicContacts': '#019a4d',
        'C': '#222',
        'N': '#3050F8',
        'O': '#FF0D0D',
        'H': '#222',
        'HE': '#D9FFFF',
        'LI': '#CC80FF',
        'BE': '#C2FF00',
        'B': '#FFB5B5',
        'F': '#90E050',
        'NE': '#B3E3F5',
        'NA': '#AB5CF2',
        'MG': '#7CE500',
        'AL': '#BFA6A6',
        'SI': '#F0C8A0',
        'P': '#FF8000',
        'S': '#F7DE3A',
        'CL': '#1FF01F',
        'AR': '#80D1E3',
        'K': '#8F40D4',
        'CA': '#33D800',
        'SC': '#E6E6E6',
        'TI': '#BFC2C7',
        'V': '#A6A6AB',
        'CR': '#8A99C7',
        'MN': '#9C7AC7',
        'FE': '#E06633',
        'CO': '#F090A0',
        'NI': '#50D050',
        'CU': '#C88033',
        'ZN': '#7D80B0',
        'GA': '#C28F8F',
        'GE': '#668F8F',
        'AS': '#BD80E3',
        'SE': '#FFA100',
        'BR': '#A62929',
        'KR': '#5CB8D1',
        'RB': '#702EB0',
        'SR': '#00FF00',
        'Y': '#94FFFF',
        'ZR': '#94E0E0',
        'NB': '#73C2C9',
        'MO': '#54B5B5',
        'TC': '#3B9E9E',
        'RU': '#248F8F',
        'RH': '#0A7D8C',
        'PD': '#006985',
        'AG': '#C0C0C0',
        'CD': '#FFD98F',
        'IN': '#A67573',
        'SN': '#668080',
        'SB': '#9E63B5',
        'TE': '#D47A00',
        'I': '#940094',
        'XE': '#940094',
        'CS': '#57178F',
        'BA': '#00C900',
        'LA': '#70D4FF',
        'CE': '#FFFFC7',
        'PR': '#D9FFC7',
        'ND': '#C7FFC7',
        'PM': '#A3FFC7',
        'SM': '#8FFFC7',
        'EU': '#61FFC7',
        'GD': '#45FFC7',
        'TB': '#30FFC7',
        'DY': '#1FFFC7',
        'HO': '#00FF9C',
        'ER': '#00E675',
        'TM': '#00D452',
        'YB': '#00BF38',
        'LU': '#00AB24',
        'HF': '#4DC2FF',
        'TA': '#4DA6FF',
        'W': '#2194D6',
        'RE': '#267DAB',
        'OS': '#266696',
        'IR': '#175487',
        'PT': '#D0D0E0',
        'AU': '#FFD123',
        'HG': '#B8B8D0',
        'TL': '#A6544D',
        'PB': '#575961',
        'BI': '#9E4FB5',
        'PO': '#AB5C00',
        'AT': '#754F45',
        'RN': '#428296',
        'FR': '#420066',
        'RA': '#007D00',
        'AC': '#70ABFA',
        'TH': '#00BAFF',
        'PA': '#00A1FF',
        'U': '#008FFF',
        'NP': '#0080FF',
        'PU': '#006BFF',
        'AM': '#545CF2',
        'CM': '#785CE3',
        'BK': '#8A4FE3',
        'CF': '#A136D4',
        'ES': '#B31FD4',
        'FM': '#B31FBA',
        'MD': '#B30DA6',
        'NO': '#BD0D87',
        'LR': '#C70066',
        'RF': '#CC0059',
        'DB': '#D1004F',
        'SG': '#D90045',
        'BH': '#E00038',
        'HS': '#E6002E',
        'MT': '#EB0026',
        'DS': '#FFFFFF',
        'RG': '#FFFFFF',
        'CN': '#FFFFFF',
        'UUT': '#FFFFFF',
        'FL': '#FFFFFF',
        'UUP': '#FFFFFF',
        'LV': '#FFFFFF',
        'UUH': '#FFFFFF',
        'D': '#FFFFC0',
        'T': '#FFFFA0'
    },
    'selectorOpacity': 1,
    'selectorDashArray': 4,
    'selectorDashWidth': 3,
    'mirrorLineWidth': 0.65,
    'piPiRadius': 3.75,
    'drawAreaPadding': 15,
    'decimalPrecision': 8,
    'svgElementOrder': [
        'hydrophobicContactSelectors',
        'cationPiStackingsSelectors',
        'piStackingsSelectors',
        'atomPairInteractionsSelectors',
        'hydrophobicContacts',
        'distances',
        'interactions',
        'cationPiStackings',
        'piStackings',
        'atomPairInteractions',
        'distancesSelectors',
        'interactionsSelectors',
        'bondSelectors',
        'atomSelectors',
        'annotationSelectors',
        'structureCirclesSelectors',
        'bonds',
        'atoms',
        'annotations',
        'structureCircles',
        'bondDebugTexts',
        'atomDebugTexts'
    ],
    'penalties': {
        'coordinateOverlap': 1000,
        'mainDrawingOverlap': 50,
        'otherDrawingOverlap': 10,
        'edgeMainDrawingOverlap': 20,
        'edgeOtherDrawingOverlap': 10,
        'smallestAngleWithoutPenalty': 30,
        'smallestAllowedAngle': 20,
        'thirtyDegreeAngleViolation': 5,
        'smallAngleViolations': 10,
        'heavyAngleViolations': 100,
        'nonCyclicEdgeHits': 50,
        'oneCyclicEdgeHits': 10,
        'cyclicEdgeHits': 10,
        'hiddenEdges': 200,
        'allowedEdgeLengthDifference': 1 / 3,
        'edgeLengthViolations': 10
    }
};
